# Generated by Django 3.0.5 on 2020-04-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='intructions',
            new_name='instructions',
        ),
    ]
